from downloader import VideoDownload
lis = [""]
songs = [ #"high hopes panic! at the disco",
#        "fireflies owl city",
#        "counting stars onerepublic",
#        "i aint worried onerepublic",
#        "somebody that i used to know gotye",
#        "payphone maroon 5",
#        "animals maroon 5",
#        "closer chainsmokers",
#        "friends marshmellow",
#        "uma thurman fall out boy",
#        "eastside benny blanco",
#        "cake by the ocean dnce",
#        "sunflower post malone",
#        "immortals fall out boy",
#        "good time owl city",
#        "best day of my life american authors",
#        "i want it that way backstreet boys",
#        "starships nicki minaj",
#        "i had some help post malone",
#        "levitating dua lipa dababy",
#        "burn ellie goulding",
#        "the other side hugh jackman",
#        "rewrite the stars zac efron",
#        "the greatest show hugh jackman",
#        "call me maybe carly rae jepsen",
#        "love story taylor swift",
#        "mr brightside the killers",
#        "mood 24kgoldn",
#        "sunroof nicky youre",
#        "overture/and all that jazz catherine zeta-jones",
#        "hall of fame the script",
#        "sweet but psycho ava max",
#        "magic bob",
#        "replay iyaz",
#        "handclap fitz and the tantrum",
#        "night changes one direction",
#        "all the stars kendrick lamar",
#        "humble kendrick lamar",
#        "squabble up kendrick lamar",
#        "havana camila cabelo",
#        "dance the night dua lipa",
#        "blue yung kai",
#        "sunshine onerepublic",
#        "still falling for you ellie goulding",
#        "unwritten natasha bedingfield",
#        "22 taylor swift",
#        "montero lil nas x",
#        "die with a smile lady gaga",
#        "leave the door open bruno mars",
#        "riptide vance joy",
#        "im still standing elton john",
#        "die young kesha",
#        "from the start laufey",
#        "about last night yel",
#        "falling behind laufey",
#        "beautiful stranger laufey",
#        "buzzkill lyn lapid",
#        "let you break my heart laufey",
#        "vampire olivia rodrigo",
#        "pink pony club chappell roan",
#        "in the stars benson boone",
#        "just the way you are bruno mars",
#        "heat waves glass animals",
#        "stay the kid laroi",
#        "blinding lights the weeknd",
#        "can't hold us macklemore",
#        "thats what i want lil nas x",
#        "2002 anne-marie"
#     "a cyber's world toby fox",
#     "welcome to the city toby fox",
#     "attack of the killer queen toby fox",
#     "big shot toby fox",
#     "snowdin town toby fox",
#     "finale toby fox",
#     "megalovania toby fox",
#     "another hopeful tomorrow yu peng chen",
#     "termination of desires hoyo-mix",
#     "liyue li-peng chen",
#     "myths you forgot camellia",
#     "pigstep lena raine",
#     "otherside lena raine",
#     "field of hopes and dreams toby fox",
#     "pandora palace toby fox",
#     "rude buster toby fox",
#     "nerves atsuover",
#     "the world revolving toby fox",
#     "checker dance toby fox",
#     "smart race toby fox",
#     "sans. toby fox",
#     "death by glamour toby fox",
#     "lovers oath yu peng chen",
#     "rex incognito yu peng chen",
#     "doodle zach winner",
#     "carnival overture dvorak",
#     "il vento d oro yugo kanno",
#     "symphony no 9 dvorak vienna movement 4",
#     "genshin impact main theme yu peng chen",
#     "american in paris gershwin",
#     "reunited toby fox",
#     "icarus tony ann",
#     "stardew valley overture concernedape",
#     "life force ptasinski",
#     "auguries of innocence william pitts",
#     "winter wind chopin",
#     "ballade no 1 chopin"
#     "知否知否 hu xia",
#     "凉凉 aska yang",
#     "小苹果 筷子兄弟",
#     "芒种 赵方婧音阙诗听",
#     "一翦梅 Fei Yu-ching",
#     "無名之輩 (電視劇《親愛的, 熱愛的》主題曲) 陳雪燃",
#     "你的答案 阿冗",
#     "光的方向 (電視劇《長歌行》片頭主題曲) Zhang Bichen",
#     "少年 梦然",
#     "蝴蝶飛呀 小虎隊",
#     "愛 小虎隊".
#     "KICK BACK Kenshi Yonezu",
#     "残響散歌 aimer",
#     "kaikai kitan eve",
#     "夜に駆ける yoasobi",
#     "night dancer imase",
#     "オレンジ 7!!",
#     "打上花火 daoko",
#     "last stardust aimer",
#     "odo ado",
#     "usseewa ado",
#     "miku anamanaguchi",
#     "千本桜 ado",
#     "guren no yumiya tv size linked horizon",
#     "ベテルギウス yuuri",
#     "aLIEz sawanohiroyuki[nZk]",
#     "dried flowers ado",
#     "eutopia 鐘 嵐珠 (CV.法元明菜)",
#     "do u takanashi kiara",
#     "antifragile le sserafim",
#     "love ka? ado",
#     "night sky patrol of tomorrow orangestar",
#     "マイナーピース zaq",
#     "mirror ado",
#     "アディオス dazbee",
#     "第六感 reol",
#     "specialz king gnu",
#     "0 ado",
#     "bite me enhypen",
#     "sparkle radwimps",
#     "zenzenzense radwimps",
#     "unravel ado",
#     "undead yoasobi",
#     "drop 美波",
#     "apt. rosé",
#     "suzume radwimps",
#     "episode x ado",
#     "crazy le sserafim",
#     "elf ado"
    ]

for i in songs:
    print(i)
    a = VideoDownload(i, search=True)
    a.download()
    lis.append(a.uid)

